#!/bin/sh

BR="make -C buildroot BR2_EXTERNAL=../PCBA O=../PCBA/output"

case "$1" in
    start)
	$BR distclean funkey_defconfig
    ;;
    update)
	$BR savedefconfig linux-update-defconfig uboot-update-defconfig busybox-update-config
    ;;
    *)
	$BR $*
    ;;
esac
