#!/bin/sh

THIS=$(basename $0)

case "$1" in
    start)

    # Check is SWAP partition already created
    fdisk -l /dev/mmcblk0 | grep "Linux swap" > /dev/null
    if [ $? -ne 0 ]; then
        first_boot
        exit $?
    fi

    # Check is share partition already created
    fdisk -l /dev/mmcblk0 | grep "W95 FAT32" > /dev/null
    if [ $? -ne 0 ]; then
        first_boot
        exit $?
    fi
	;;
    stop)
	;;
    *)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac
