#!/bin/sh

# Uncomment the following line to get debug info
#set -x

source /usr/local/lib/utils

SELF=$(basename $0)

# Find out the root partition number from the kernel command line
root_part=$(cat /proc/cmdline | sed -n 's|^.*root=/dev/\([^ ]*\).*|\1|p')
root_part_num=${root_part#mmcblk0p}
if [ "${root_part_num}" -eq 1 ]; then
    die 0 "recovery mode"
elif [ "${root_part_num}" = "{$root_part}" ]; then
    die 1 "${root_part} is not an SD card partition, aborting"
elif [ "${root_part_num}" -ne 2 ]; then
    die 2 "unknown partition layout, aborting"
fi

check_swap () {
    [ -f /swap ] && die 0 "nothing to do"
    return 0
}

check_root_id () {
    [ $(id -u) -ne 0 ] && die 3 "this script must be run as root, aborting"
    return 0
}

resize_rootfs_partition () {

    # Check that the last partition is the rootfs partition
    local last_part_line=$(sgdisk -p /dev/mmcblk0 | tail -n 1)
    set ${last_part_line}
    local last_part=${1}
    if [ "${last_part}" != "${root_part_num}" ]; then
	die 4 "rootfs is not the last partition. Don't know how to expand, aborting"
    fi

    # Remove (temporarily) the rootfs partition
    sgdisk -d ${root_part_num} /dev/mmcblk0 >/dev/null 2>&1 || die 5 "cannot remove the rootfs partition, aborting"

    # Re-create the rootfs partition with a 1GB size
    sgdisk -n ${root_part_num}:0:+1G -c ${root_part_num}:rootfs /dev/mmcblk0 >/dev/null 2>&1 || die 6 "cannot resize the rootfs partition, aborting"

    # Mark the rootfs partition as bootable
    sgdisk -A ${root_part_num}:set:2 /dev/mmcblk0 >/dev/null 2>&1 || die 7 "cannot make the rootfs partition bootable, aborting"

    # Copy the primary GPT to the end of the disk
    sgdisk -e /dev/mmcblk0 >/dev/null 2>&1 || die 8 "cannot move the GPT to the end of the disk"
    sync
    return 0
}

reload_partition_table () {
    partprobe /dev/mmcblk0 >/dev/null 2>&1 || die 9 "cannot reload the partition table, aborting"
    return 0
}

resize_rootfs_filesystem () {
    resize2fs /dev/${root_part} >/dev/null 2>&1 || die 10 "cannot resize the root filesystem, aborting"
    return 0
}

create_swap_file () {
    local root_part_line=$(df | grep /dev/root)
    set ${root_part_line}
    local space_left=${4}
    if [ ${space_left} -lt 131072 ]; then
	die 12 "not enough free space for swap file found, aborting"
    fi

    # Create an empty 128MB /swap file, change its permissions and format it as swap
    dd if=/dev/zero of=/swap bs=32M count=4 >/dev/null 2>&1 &&
	chmod 0600 /swap >/dev/null 2>&1 &&
	mkswap /swap >/dev/null 2>&1
    if [ $? -ne 0 ]; then
	rm /swap
	die 13 "cannot create swap file, aborting"
    fi
    return 0
}

enable_swap_file () {
    swapon -a >/dev/null 2>&1 || die 14 "cannot enable swap file, aborting"
    return 0
}

create_backing_store_partition () {
    mount | grep -q /dev/mmcblk0p3
    if [ $? -ne 0 ]; then

	# Check that the last partition is the rootfs partition
	local last_part_line=$(sgdisk -p /dev/mmcblk0 2>/dev/null | tail -n 1)
	set ${last_part_line}
	local last_part=${1}
	if [ "$last_part" != "$root_part_num" ]; then
	    die 15 "rootfs is not the last partition. Don't know how to create the backing store partition"
	fi

	# Create an additional Microsoft basic data partition share partition that fills the disk
	let share_part=${last_part}+1
	sgdisk -n ${share_part}:0:-0 -c ${share_part}:share -t ${share_part}:0700 /dev/mmcblk0 >/dev/null 2>&1 || die 16 "cannot create the backing store partition, aborting"
	sync
    fi
    return 0
}

format_backing_store_partition () {

    # Format the backing store as FAT32
    mkfs.vfat /dev/mmcblk0p3 >/dev/null 2>&1 || die 17 "cannot format the backing store partition"
    
    # Add file to force assembly tests 
    mount /mnt/ || die 18 "Cannot mount /mnt"
    touch /mnt/.assembly_tests || die 19 "Cannot create assembly tests run file"
    umount /mnt/ || die 20 "Cannot unmount /mnt"
    return 0
}

notif "First boot detected!"
check_swap
check_root_id

notif "1/8 Resize root partition"
resize_rootfs_partition

notif "2/8 Reload partition table"
reload_partition_table

notif "3/8 Resize root filsystem"
resize_rootfs_filesystem

notif "4/8 Create swap"
create_swap_file

notif "5/8 Enable swap"
enable_swap_file

notif "6/8 Create share partition"
create_backing_store_partition

notif "7/8 Reload partition table"
reload_partition_table

notif "8/8 Format share partition"
format_backing_store_partition

notif "First boot setup finished!"
sleep 1
clear_notif
