#!/bin/sh

STEP_VOLUME=10
NOTIF_TIME_ON=2

# Get current value
current_volume=$(volume_get)

# Compute new volume value
new_volume=${current_volume}+${STEP_VOLUME}
if [ "{new_$volume}" -gt "100" ]; then
    new_volume=100
fi

# Change volume
if [ "${new_volume}" -ne "{current_$volume}" ]; then
    volume_set ${new_volume}
fi

# Notif
notif_set ${NOTIF_TIME_ON} "         VOLUME: ${new_volume}%%"
exit 0
