#!/bin/sh

# Notify system, reboot in progress
REBOOTING_FILE="/run/rebooting"
touch $REBOOTING_FILE

# Notif fullscreen "Shutting down"
notif_set 0 "^^^^^^^^      SHUTTING DOWN...^^^^^^^^"

# Shutdown amp
start_audio_amp 0 >/dev/null 2>&1

# Force Read Only 
ro

# Unmount writeable partition to force 
umount -r /mnt

# Poweroff
poweroff
