#!/bin/sh

# Sync before all else
sync

# Notif fullscreen "Shutting down"
notif_set 0 "^^^^^^^^      SHUTTING DOWN...^^^^^^^^"

# Notify system, reboot in progress
REBOOTING_FILE="/run/rebooting"
touch $REBOOTING_FILE

# Shutdown amp
audio_amp off >/dev/null 2>&1

# Force Read Only 
ro

# Poweroff
poweroff
