#!/bin/sh
# This should replaced by storing the correct PID before 
# launching an emulator and signaling only this one.

killall -s USR1 mednafen gpsp psnes pcsx sdlgnuboy PicoDriveBin >/dev/null 2>&1
exit 0
