#!/bin/sh

# Uncomment the following line to get debug info
#set -x

LOCK_FILE="/var/lock/launcher.lock"
INSTANT_PLAY_FILE="/mnt/instant_play"
PREVENT_LAUNCHER_FILE="/mnt/prevent_launcher"
GMENU2X_FILE="/mnt/gmenu2x"
GMENU2X_HOME="/mnt/funkey/.gmenu2x"

if [ -f "${LOCK_FILE}" ]; then
    echo "${LOCK_FILE} already exists"
    exit 1
fi
touch "${LOCK_FILE}"

mkdir -p "${MEDNAFEN_HOME}"
cp "/usr/games/lynxboot.img" "/usr/games/mednafen-09x.cfg" "${MEDNAFEN_HOME}/"

mkdir -p "${GMENU2X_HOME}"
mkdir -p "/mnt/apps"

# Launch Previous Game if any
if [ -f "${INSTANT_PLAY_FILE}" ]; then
    echo "Found Instant Play file, restarting previous game with command: "$(head -n 1 "${INSTANT_PLAY_FILE}")
    source "${INSTANT_PLAY_FILE}"
    rm -f "${INSTANT_PLAY_FILE}"
    termfix_all
fi

# Then loop to launch the launcher indefinitely
while true; do
	
    # Check if prevent launcher file present
    if [ -f "${PREVENT_LAUNCHER_FILE}" ]; then
		echo "${PREVENT_LAUNCHER_FILE} file found, not starting launcher" 
		sleep 5
    else
		if [ -f "${GMENU2X_FILE}" ]; then

		    # Launch gmenu2x
		    gmenu2x&
		else

		    # Launch Retrofe
		    retrofe&
		fi

		# Record the PID into a file, wait for the
		# process to terminate and erase the recorded PID
		record_pid $!
		wait $!
		erase_pid

		# In case retrofe quits with errors, clear graphic VT
		termfix_all
    fi
done
rm "${LOCK_FILE}"
exit 0
