#!/bin/sh

# Write quick load file args
QUICK_LOAD_FILE=/mnt/quick_load_cmd

echo -n "" > $QUICK_LOAD_FILE
for i in "$@"; do
    if $(echo "$i" | egrep -q '[[:space:]]'); then

	# Add quotes around arguments containing spaces
        echo -n "\"$i\" " >> ${QUICK_LOAD_FILE}
    else
	echo -n "$i "  >> ${QUICK_LOAD_FILE}
    fi
done
echo "" >> ${QUICK_LOAD_FILE}

exit 0
