#!/bin/sh

# Notif fullscreen "Shutting down"
notif set 0 "^^^^^^^^      SHUTTING DOWN...^^^^^^^^"

# Kill Emulators
#kill_emulators >/dev/null 2>&1

# Kill Retrofe
#pkill retrofe

# Sync filesystems (useful in case poweroff could not finish)
sync

# Unmount Roms partition
#umount /mnt

# Shutdown amp
start_audio_amp 0 >/dev/null 2>&1

# Poweroff
poweroff
