#!/bin/sh

# Uncomment the following line to get debug info
#set -x

# Check args
if [ ${#} -ne 0 ]; then
    echo "Usage: $(basename ${0})"
    exit 1
fi

# Lock file (necessary since fbgrab must run in bg not to block the buttons while gaming)
LOCK_FILE="/var/lock/snap.lock"
if [ -f "${LOCK_FILE}" ]; then
    echo "${LOCK_FILE} already exists"
    exit 1
fi
touch "${LOCK_FILE}"

# Increment name and save snapshot
SNAPSHOT_EXT=PNG
SNAPSHOT_DIR=/mnt/FunKey/snapshots
mkdir -p "${SNAPSHOT_DIR}"
last=$(cd ${SNAPSHOT_DIR}; ls IMG_*.${SNAPSHOT_EXT} 2> /dev/null | tail -1 | sed 's/^IMG_0*\([0-9]\+\)\.'${SNAPSHOT_EXT}'$/\1/')
let last=${last}+1
snapshot_file=$(printf "IMG_%04d.${SNAPSHOT_EXT}" $last)
notif set 2 "   SCREENSHOT ${snapshot_file}"
fbgrab "${SNAPSHOT_DIR}/${snapshot_file}" >/dev/null 2>&1 &

# Remove lock file
rm -f "${LOCK_FILE}"

exit 0
