#!/bin/sh
#
# Start/stop funkey_gpio_management
#

DAEMON=/usr/local/sbin/funkey_gpio_management
PIDFILE=/var/run/funkey_gpio_management.pid

case "$1" in
  start)
	echo -n "Starting funkey_gpio_management: "
	start-stop-daemon -S -x ${DAEMON} -p ${PIDFILE} -m -b -- > /dev/null 2>&1
	if [ ${?} -eq 0 ]; then
	  echo "OK"
	else
	  echo "ERROR"
	fi
	;;
  stop)
	echo -n "Stopping funkey_gpio_management: "
	start-stop-daemon -K -x ${DAEMON} -p ${PIDFILE} -o > /dev/null 2>&1
	if [ ${?} -eq 0 ]; then
	  echo "OK"
	else
	  echo "ERROR"
	fi
	;;
  restart)
	${0} stop
	sleep 1 # Prevent race condition: ensure funkey_gpio_management stops before start.
	${0} start
	;;
  *)
	echo "Usage: ${0} {start|stop|restart}"
	exit 1
esac
