#!/bin/sh
modprobe g_ether
HOST_USB_IP=10.0.1.1
TARGET_USB_IP=10.0.1.2
ifconfig usb0 $TARGET_USB_IP netmask 255.255.255.0
route add default dev usb0
route add default gw $HOST_USB_IP
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
RSA_KEYFILE=/etc/dropbear/dropbear_rsa_host_key
dropbearkey -t rsa -f $RSA_KEYFILE
